REM   Script: Session 02
REM   alter tabkle

1a. ALTER TABLE PROJETO ( 


	ADD STATUS numeric (1) NOT NULL, 


	CONSTRAINT CK_STATUS CHECK (STATUS IN (0, 1)) 


) 


b.ALTER TABLE PROJETO ( 


    MODIFY TITULO_PROJ varchar (252) 


) 


C. ALTER TABLE PROJETO RENAME COLUMN DATA_CAD TO DATA_CADASTRO


2a. ALTER TABLE FUNCIONARIO DROP COLUNM ENDERECO; 


CREATE TABLE ENDERECO ( 
	cod_endereco numeric (4), 
	rua varchar (40), 
	cep varchar (8), 
	bairro varchar (40) 
 
);

CREATE TABLE FUNC_ENDERECO ( 
	COD_FUNC number (4) constraint FK_FUNC_COD_ENDERECO references FUNCIONARIO (COD_FUNC), 
    COD_ENDERECO number(4) constraint FK_FUNC_END_COD_ENDERECO references ENDERECO(COD_ENDERECO), 
    constraint FUNC_ENDERECO primary key (COD_FUNC, COD_ENDERECO) 
) 
 
 
 
 
 
b.ALTER TABLE FUNCIONARIO  
DROP CONSTRAINT CK_SALARIO;

c.ALTER TABLE FUNCIONARIO  


DISABLE CONSTRAINT UK_CPF CASCADE; 


ALTER TABLE FUNCIONARIO 
ENABLE CONSTRAINT UK_CPF CASCADE;

d.ALTER TABLE FUNCIONARIO  


DISABLE CONSTRAINT PK_COD_FUNC CASCADE; 


ALTER TABLE FUNCIONARIO 
ENABLE CONSTRAINT PK_COD_FUNC CASCADE;

3.a 


ALTER TABLE DEPENDENTE drop column DP_PARENTESCO;

CREATE TABLE PARENTESCO ( 
    PAREN_COD number (4) contraint FK_PARENTESCO_PAREN-COD primary key, 
    PAREN_DESCRICAO varchar(20) constraint CK_PAREN_DESCRICAO check (PAREN_DESCRICAO in ('pai','mãe','irmaos','filho')) not null 
);

ALTER TABLE DEPENDENTE add PAREN_COD constraint FK_DEPENDENTE_PAREN_COD references PARENTESCO (PAREN_COD);

b.  


ALTER TABLE DEPENDENTE add DP_CPF varchar (12);

ALTER TABLE DEPENDENTE add constraint UK_DEPENDENTE_DP_CPF unique (DP_CPF);

SELECT * FROM DEPENDENTE;

c. 


ALTER TABLE DEPENDENTE drop constraint FK_DEPENDENTE_DP-FUNC_COD cascasde;

ALTER TABLE DEPENDENTE add constraint FK_DEPENDENTE_DP_FUNC_COD_ foreign key (DP_FUNC_COD) references FUNCIONARIO (FUNC_COD) on delete cascade;

4. 


ALTER TABLE PARTICIPA RENAME TO FUNC_PROJETO;

